# Generated by Django 4.2.7 on 2023-12-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitch_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwitchUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("twitch_id", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField()),
                ("affiliated", models.BooleanField()),
                ("language", models.CharField(max_length=50)),
                ("mature", models.BooleanField()),
                ("updated_at", models.DateTimeField()),
            ],
        ),
    ]
